source/d3d8to9_device.cpp, source/d3d8to9_index_buffer.cpp, source/d3d8to9_surface.cpp, source/d3d8to9_texture.cpp, source/d3d8to9_vertex_buffer.cpp, source/d3d8to9_volume.cpp
It could solve issues with inconsistent device refcounters in games which expect d3d8 to be thread safe.
=> Atomic refcounters, fixed device release

source/d3d8to9.hpp, source/d3d8to9_device.cpp, source/d3d8types.hpp
Compiling with v140 toolsets in /MT mode (I don't want to rely on VS2015 redist packages) gives me a RIDICULOUS amount of hits on virustotal:
https://www.virustotal.com/file/ecd4935c5a3b653062a648674c6856cbd47edd33e6f5c7e64a4277054ec261c9/analysis/1480277016/
The issue seems to be real since within 24h from the moment the update with this DLL went live I saw numerous people reporting their AVs block the game...
Oddly enough, if I remove file logging OR switch to Clang, all those hits are gone. MS's Clang requires some slight changes to the code though, so there it is. v140 still compiles fine, of couse.
=> Fix Clang compilation

source/d3d8to9_base.cpp, source/d3d8types.cpp
- Removed "device->SetFVF(D3DFVF_XYZ);" line from Direct3D8::CreateDevice.  This fixes an issue with game Haegemonia Legions of Iron.  It seems there is no need to declare a default vertex here.   According to Microsoft documentation D3D8 applications should  call SetVertexShader API before using a vertex and SetFVF  already called when an application calls SetVertexShader.  https://msdn.microsoft.com/en-us/library/windows/desktop/bb204851(v=vs.85).aspx#Vertex_Declaration_Changes
- Minor updates to convert_caps and convert_surface_desc to simplify code.
- Updates to convert_present_parameters for better d3d9 copmatibility.
- Updated logic for when MultiSampleType should be set to D3DMULTISAMPLE_NONE.
- Changed PresentationInterval to default to D3DPRESENT_INTERVAL_ONE, the normal d3d9 …
=> Update to fix graphic issues with Haegemonia and enhance compatibility

d3d8to9.vcxproj, source/d3d8to9_device.cpp
d3dx8_43.dll was loaded statically before.  Some systems have different versions of this dll.  Changed it to load dynamically based on the version available on the system.
Note: This is also done by other programs.  Check out the log from ts3overlay [here](https://pastebin.com/s8RWZExL).
=> Make d3dx9_xx.dll load dynamically

d3d8to9.vcxproj, source/d3d8to9.cpp, source/d3d8to9.hpp, source/d3d8to9_device.cpp, source/d3d8to9_index_buffer.cpp, source/d3d8to9_surface.cpp, source/d3d8to9_texture.cpp, source/d3d8to9_vertex_buffer.cpp, source/d3d8to9_volume.cpp
With this change, underlying d3d9 resources don't have their refcounts changed by wrapper's `AddRef` and `Release` and instead they only get released once at wrapper destruction time. Instead of returning underlying resource's refcount from wrapper functions, now wrapper's refcounts are returned. This fixes cases where the game is doing something like
```c++
while(resource->Release() > 0);
```
Might also be a micro optimization since it issues less d3d calls (albeit refcount ones should be nearly no-ops).
Fixes #19
=> Alternate refcounting method

source/d3d8to9.cpp
Added a message box when d3d8to9 is unable to load d3dx9_43.dll. It asks users to download the Microsoft DirectX® End-User Runtime, and also allows to ignore the warning when the "cancel" button is clicked.
=> Message box when failed to load d3dx9_43.dll

source/d3d8to9_device.cpp
Added `(?![0-9])` to ensure that all the numbers get picked up in a multi-digit register name when translating vector and pixel shaders.
This fixes the issue reported in [#28](https://github.com/crosire/d3d8to9/issues/28).
=> Fix shader translation for Star Wars Republic Commando

source/d3d8to9.hpp, source/d3d8to9_base.cpp
This update will cache AdapterModes to reduce number of Direct3D9 API calls.  This solves major performance issue on startup when using WineD3D.  See issue [#24](https://github.com/crosire/d3d8to9/issues/24).
The issue was that for each call to `EnumAdapterModes` d3d8to9 would make multiple calls to `GetAdapterModeCount`.  This would multiply the number of API calls significantly.  Furthermore, it seems there is a slight delay for each of these API calls when using WineD3D.  Calling them only once and caching the results significantly improves the performance.
This update will make is to that when a Direct3D8 device is created it will enum all adapter modes and store them in a vector.  Then when the game calls `EnumAdapterModes` it will retrieve them from the vector.
=> Cache AdapterModes to reduce number of Direct3D9 API calls

source/d3d8to9_index_buffer.cpp, source/d3d8to9_vertex_buffer.cpp
Update the Lock() functions for Vertex and Index Buffers so that they ignore the `D3DLOCK_DISCARD` flag if the `D3DUSAGE_WRITEONLY` flag is not set.  Fixes the missing texture issue with [Raymond 3](https://github.com/crosire/d3d8to9/issues/14).
=> Fix Vertex and Index Buffer Locks that don't use D3DUSAGE_WRITEONLY

source/d3d8to9_device.cpp
- Minor updates in vertex and pixel shaders regex to merge two negative lookbacks into one and slightly reduce the complexity of the regex
- Added code to get the arithmetic count in use
- Updated regex code that changes 'add' with a '-' modifier to 'sub' to make it more generic and work with swizzles and modifiers
- Added code to generically update any modifier on a constant by using the extra arithmetic functions available, this fixes one of the lighting issues with Star Wars Republic Commando
- Added code that changes 'mad' with a '-' modifier to 'sub', this fixes one of the lighting issues with Star Wars Republic Commando
- Added code that changes '_bx2' source modifier for constant to use _x2 destination modifier, this fixes a minor lighting issue with Silent Hill 2
This update …
=> Update pixel shader translations to fix lighting issues

source/d3d8to9.cpp, source/d3d8to9_base.cpp, source/d3d8to9_device.cpp
This fix has several changes it in:
1. Error with lost device when CreateDevice is called:
The core issue with GTA III/VC mentioned in #39 is that GTA would try and create a new device when the old device was still there.  This caused it to return error `D3DERR_DEVICELOST`.  However GTA does not know how to properly handle this error and simply crashed.  The fix is to call `Release()` to release the previous device when a device lost error is seen so that a new device can be created.
It also seems that after the new device is created then GTA VC will call `Release()` and release the old device.  So this update will release the Direct3D9 device.  When GTA VC calls `Release()` then the Direct3D8 device (d3d8to9) will get released.
2. Invalid display type listed with 0-bits of color:
When …
=> Fix device lost error when creating device to fix issue with GTA III/VC

source/d3d8to9_device.cpp
This update will check the VertexShader instruction count before adding any more instructions to the shader to ensure that the count never exceeds 128 instructions.  This will fix the issue with d3d8to9 and BloodRayne/BloodRayne 2.  See comments on these two threads:
- [Anyone get Reshade and Bloodrayne working?](https://reshade.me/forum/troubleshooting/973-bloodrayne-bloodrayne-2)
- [Unofficial "FSAA Patch" crashes on Windows 8/10](https://github.com/elishacloud/dxwrapper/issues/7)
A few notes here:
1. Initialization of the output registers are not always needed because sometimes (like the case with BloodRayne) they are already initialized in the existing VertexShader from the game.
2. It seems that only initialization of the oT (Texture Coordinate) register is actually needed.  I have …
=> Check VertexShader instruction count

source/d3d8to9_base.cpp, source/d3d8to9_device.cpp, source/d3d8to9_index_buffer.cpp, source/d3d8to9_surface.cpp, source/d3d8to9_swap_chain.cpp, source/d3d8to9_texture.cpp, source/d3d8to9_vertex_buffer.cpp, source/d3d8to9_volume.cpp, source/lookup_table.cpp, source/lookup_table.hpp
This update will fix a couple of issues with the reference counter.  This fixes the crash in [GTA III/VC](https://github.com/crosire/d3d8to9/issues/39) when changing resolutions and the crash in [Serious Sam 1 & 2](https://github.com/crosire/d3d8to9/issues/39#issuecomment-323473718) when pressing alt+tab.
There are several fixes in this update:
1. This update stops adding a reference the constructor and releasing the reference in each destructor.
These extra references are not needed.  Plus they complicate the code and masks other issues (see below).  Also it seems like d3d8to9 does not always close out all the references here, though I cannot prove this.  This seems to be the main issue because the reason the games were crashing is because the previous device was still open and the …
=> Update Ref Count

source/d3d8to9_device.cpp
Ok, I believe this is finally ready to check in.  This has a few different updates in it, but the biggest change is the code to convert to ps_1_4.  Let me describe the other changes first.
Sorry for the wall of text!
**1. Added some spaces to make the code more readable**
See [here](https://github.com/crosire/d3d8to9/compare/master...elishacloud:Convert-to-ps_1_4?expand=1#diff-366bc9823b5fedd9a67231f1896c4f8fR2000) and [here](https://github.com/crosire/d3d8to9/compare/master...elishacloud:Convert-to-ps_1_4?expand=1#diff-366bc9823b5fedd9a67231f1896c4f8fR2005) for an example.
**2. Changed the way Instruction/Arithmetic count is computed:**
This is a realitivly small update but I changed from using `int` to using `size_t` and I changed from using `atoi` to using `strtoul`.  This also changes …
=> Convert to ps_1_4

source/d3d8to9_base.cpp, source/d3d8to9_device.cpp, source/d3d8types.cpp
This fixes #66 and #67.
**Overview:**
There are three updates in this fix:
1. Updated CreateDevice, CreateAdditionalSwapChain, CreateRenderTarget, CreateDepthStencilSurface and Reset functions to support MultiSampleQuality by querying CheckDeviceMultiSampleType.  If MultiSampleType == D3DMULTISAMPLE_NONE then set MultiSampleQuality to 0.  Note: this is all the functions that use MultiSampling as seen [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb172574(v=vs.85).aspx).
2. Remove D3DPRESENTFLAG_LOCKABLE_BACKBUFFER flag when MultiSampleType != D3DMULTISAMPLE_NONE is detected.
3. Update unsupported D3DPRESENT_RATE_UNLIMITED flag to use D3DPRESENT_INTERVAL_IMMEDIATE rather than D3DPRESENT_INTERVAL_ONE to replicate more closely the d3d8 functionality.
**Testing:**
Tested the …
=> Fix Multisample support

source/d3d8to9_device.cpp, source/d3dx9.hpp
This pull fixes #64 and #70.  There are basically 4 changes in here:
1. Minor update of QualityLevels.
I just moved the [ternary operator](https://en.wikipedia.org/wiki/%3F:) out of the `CreateRenderTarget` and `CreateDepthStencilSurface` functions and hid it behind the if statement to clean up the code slightly.
2. Modified the PixelShader code to ensure that the swizzle comes at the end.  See comments [here](https://github.com/crosire/d3d8to9/issues/70#issuecomment-379416048).
This modifies two regex functions that remove modifiers on constants.  It adds a new regex group by changing `(r[0-9][\\.wxyz]*)` into `(r[0-9])([\\.wxyz]*)`.  This allows the swizzle to be in its own group so that we can ensure the swizzle comes last.
_Note: since a new group is added all the references to the …
=> Update Shader swizzle and debug support

source/d3d8to9_device.cpp
This fixes the comments mentioned [here](https://github.com/crosire/d3d8to9/issues/70#issuecomment-381148614) by @PatrickvL. This check-in removes the swizzle from the modified line while keeping the swizzle in the added `mov` line.
Since it keeps the swizzle on the `mov` line it still allows for the closest possible conversion.
However, it needs to remove the swizzle from the source modifier because not all source modifiers can be used together with a swizzle.  Note: a swizzle is just another form of a source modifier.
See documentation [here](https://msdn.microsoft.com/en-us/library/windows/desktop/bb219868(v=vs.85).aspx):
> * Negate can be combined with either the bias, signed scaling, or scalex2 modifier. When combined, negate is run last.
> * Invert cannot be combined with any other …
=> Remove swizzle from changed lines

source/d3d8to9.hpp, source/d3d8to9_base.cpp, source/d3d8to9_device.cpp, source/lookup_table.cpp
This PR consists of two commits,:
- One is a random code quality improvement - no point to clear containers explicitly in destructors as they are about to be destructed anyway.
- The main commit implements clip plane cache as an attempt to work around a possible D3D9 (and maybe D3D8) issue, as referenced in those places:
https://reshade.me/forum/troubleshooting/4165-d3d9-regression-with-clip-planes-affects-far-cry
https://github.com/elishacloud/dxwrapper/issues/5#issuecomment-378371756
https://github.com/CookiePLMonster/SilentPatchFarCry/commit/fb79e575e7cb9f9d07a8f35733be4b41caa69dca
https://www.vogons.org/viewtopic.php?f=8&t=40913&start=120#p661929
While D3D8 itself may not be affected by this issue, it will be affected with d3d8to9 (because D3D9, duh), so it makes sense to ship that. …
=> Implemented clip planes cache

source/d3d8to9_base.cpp
This pull request fixes issue #42.
This change will return `D3DERR_NOTAVAILABLE` when an application queries using `CheckDeviceFormat` on any texture using a YUV format.  ATI and Nvidia already return this value for textures, so it should have no affect on these GPUs.  However, some Intel chips do not.  It appears that these Intel chips attempt to handle the formats but do not handle them correctly.
I believe with Direct3D9 that YUV is supposed to be unsupported on textures.  See [comment](https://www.winehq.org/pipermail/wine-patches/2014-February/130383.html) on WineD3D:
>         /* Some (all?) Windows drivers do not support YUV 3D textures, only 2D surfaces in
>          * StretchRect. Thus use StretchRect to draw the YUV surface onto the screen instead
>          * of drawPrimitive. …
=> Disable YUV formats on textures

source/d3d8to9.hpp, source/d3d8to9_device.cpp
This pull fixes #76 and this pull fixes #79.
There are two changes here:
1. This will return D3DERR_INVALIDCALL if the pViewport describes a region that cannot exist within the render target surface.  See comments [here](https://github.com/crosire/d3d8to9/pull/78#issuecomment-389407210) for details on how this fixes the issue with Hydorah.
2. This takes the update from [here](https://github.com/Cxbx-Reloaded/d3d8to9/commit/c7236282d5c3f8ee871e26953cfdd2eeebe964cf).  This fixes an issue where D3DUSAGE_DYNAMIC was breaking Depth Stencil Textures.
I tested this with the following games:
* Codemasters Race Driver 2
* Grand Theft Auto 3
* Grand Theft Auto Vice City
* Haegemonia Legions of Iron
* Haegemonia The Solon Heritage
* Hitman 2 Silent Assassin
* Hydorah
* Indiana Jones and the …
=> Check SetViewport region and fix issue with Depth Stencil Textures

source/d3d8to9_device.cpp
Some games, like Command and Conquer Generals and Silent Hill 2 require system memory.  Other games like Forsaken World require scratch memory and will fail if system memory is used.  Trying system memory first and then scratch memory seems to work for all games.
This fixes issue #106.
=> Try D3DPOOL_SYSTEMMEM first then D3DPOOL_SCRATCH

source/d3d8to9_device.cpp, source/d3d8types.cpp
This pull request fixes #49 
This pull request fixes #63 
This pull request fixes #86 
This pull request fixes #103 
This pull also fixes [AquaNox](https://www.gog.com/game/aquanox), which never worked before with d3d8to9.
There are three main updates in this pull:
1. Fixes present parameters to match the documentation.
This will properly set the vsync based on whether the game is usin windowed or fullscreen.  This also removes the code that forced `D3DMULTISAMPLE_NONE`, as this broke some AA functions.
2. Fixes oPos register swizzles in VertexShader
AquaNox uses almost 100 VirtexShaders.  Several of them would set only  on the x and y components of the pPos register, which is not allowed in DirectX9.  See sample below.
Before fix (see error):
```asm
> Dumping translated shader assembly: …
```
=> Fix vsync, oPos register and RenderState

CMakeLists.txt, d3d8to9.vcxproj, d3d8to9.vcxproj.filters, source/d3d8.hpp, source/d3d8to9.cpp, source/d3d8to9.hpp, source/d3d8to9_base.cpp, source/d3d8to9_device.cpp, source/d3d8to9_index_buffer.cpp, source/d3d8to9_surface.cpp, source/d3d8to9_swap_chain.cpp, source/d3d8to9_texture.cpp, source/d3d8to9_vertex_buffer.cpp, source/d3d8to9_volume.cpp, source/interface_query.cpp, source/interface_query.hpp
Virtual function tables were not matching d3d8 because destructor pointer was inserted at offset 0. I wonder how this can work in MSVC...
=> Fix broken layout of virtual function tables when building with MinGW

README.md
As discussed in https://github.com/crosire/d3d8to9/issues/142#issuecomment-1109202254
Windows 10 / 11 is ignoring some of the game requests. For example, it results in disabled V-Sync in the DirectX 8 mode, while d3d8to9 actually follows the game requests. It may result in the false first-impression of performance with d3d8to9. I added some information about these differences to the README file, and also mentioned the amazing dxwrapper which could be useful for players who are trying to tweak older games, not only convert the API calls.
Some English tweaks or shortening would be welcome. I apologize if mentioning the other project is not allowed, I just thought it's a good solution to prevent creating many game-specific issues in this project, which are usually already resolved in …
=> Add an additional disclaimer to README regarding DirectX 8 differences on the new Windows versions, GPU drivers, etc.

source/d3d8to9.hpp, source/d3d8to9_device.cpp
This is a proposal to fix the issue outlined in https://github.com/crosire/d3d8to9/issues/155. Basically, D3D8.1 and D3D9 lifetimes have different rules but d3d8to9 currently doesn't follow the D3D8.1 behavior (which is that shaders share a lifetime with the device that created them and are implicitly destroyed). This causes some D3D8 applications to leak shader and device objects even if they are well behaved under plain D3D8.x.
Here is a test that shows this behavior:
[d3d8_refcounttest.zip](https://github.com/crosire/d3d8to9/files/11711248/d3d8_refcounttest.zip)
=> Shader lifetime improvement

source/d3d8to9_device.cpp
Related to #159 , it seems that some D3D8 applications will still make calls to SetVertexShader() after a Present call returns D3DERR_DEVICELOST and the device is lost. The Microsoft documentation mentioned in #155 seems to imply otherwise, but the Microsoft supplied d3d8dll seems to handle this case just fine so applications for DX8 probably just followed this behavior at the time. I am retaining the shader destruction on device release though, since in testing of d3d8.dll, shader objects don't increment the device refcount and this was causing d3d9 devices and shaders to leak under d3d8to9.
=> Revert the call to ReleaseShaders in Device::Reset.

source/d3d8to9.hpp, source/d3d8to9_device.cpp
Similarly to VS, shader definitions and PS, some games create state blocks that they never delete and expect the D3D8 runtime to perform this cleanup on device release (this doesn't happen in D3D9). Should help improve, if not completely address #92, but needs some wider testing.
=> Track and release state blocks on device release

source/d3d8to9_base.cpp, source/d3d8to9_device.cpp
This fixes a resource leak that happens in `GetTexture()` because we query for the interface after getting the texture and never release the extra reference that creates.
Also, this prevents the game from creating a pure device.  d3d8to9 won't work with a pure device because it requires many `Get` functions that won't work if a game creates a pure device.
=> Fix resource leak and prevent pure device creation

source/d3d8to9_device.cpp
I'm guessing this format swap is a remnant from the initial code, if git blame is to be believed. It should no longer be needed now, as image surfaces with R8G8B8 will be created just fine in D3DPOOL_SCRATCH, with the current fallback logic.
The swap usually works fine anyway, but has the drawback of causing minor issues at times, such as corrupting savegame screenshots in [Chrome](https://www.pcgamingwiki.com/wiki/Chrome). Keeping R8G8B8 as is solves this problem.
=> Remove CreateImageSurface R8G8B8 swap with X8R8G8B

source/d3d8to9.hpp, source/d3d8to9_device.cpp
This will fix PR #159 so shaders and state blocks are correctly released once the device reference count reaches 1.  The previous code would cause a crash on exit in a couple of games, including _Indiana Jones and the Emperor's Tomb_ and _[State of Emergency](https://github.com/elishacloud/dxwrapper/issues/254#issuecomment-2372713179)_.
This fix does the following things:
1. It fixes the ref count issue in both `AddRef()` and `Release()` to return the correct value based on how the native Direct3D8 works.
2. It cleans up some code related to the shader count in `CreateVertexShader()`
3. It fixes a crash in Windows 7 64bit caused by erasing an item in a map while looping through the same map.
I tested this with a couple of games alongside the native d3d8 to ensure it does not crash and it …
=> Reference count fix for Shaders and StateBlocks to prevent a crash when exiting games

source/d3d8to9_device.cpp
A minor nitpick, though some games may be affected by it in the end.
The default value of D3DRS_POINTSIZE_MIN in [D3D9 is 1.0f](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3drenderstatetype#constants), whereas it is 0.0f in D3D8:
This needs to be propagated both on device creation and on subsequent device resets.
Besides the documentation hinting at these defaults, I wrote a test to verify them against native d3d8 and d3d9, and they are indeed as stated (thus in need of correction).
=> Set the correct value of 0.0f for D3DRS_POINTSIZE_MIN

res/d3d8.def, source/d3d8to9.cpp
There are a few of undocumented functions exposed by d3d8.dll which are (apparently) needed by some games to function properly. Namely:
- `ValidatePixelShader()`, `ValidateVertexShader()` are needed by [Shadow of Memories/Destiny](https://en.wikipedia.org/wiki/Shadow_of_Memories), otherwise the game crashes on startup.
- `DebugSetMute()`, is needed by [C&C: Generals](https://en.wikipedia.org/wiki/Command_%26_Conquer%3A_Generals) (and its addon, Zero Hour) to perform adequently when rendering menus. For some reason the games spam calls to `DebugSetMute()` on the rendering thread (I assume) when menus are on screen (about once every frame) and that causes massive slowdowns if this function isn't exposed.
I've stubbed them for now, and that resolves both issues mentioned above. Potentially, …
=> Stub ValidatePixelShader, ValidateVertexShader and DebugSetMute

source/d3d8to9_surface.cpp, source/d3d8to9_volume.cpp
Similarly addresses a [failing Wine test](https://github.com/wine-mirror/wine/blob/master/dlls/d3d8/tests/device.c#L5857) and is inline with native D3D8 behavior.
=> Clear existing rect/volume content on surface/volume locks

source/d3d8to9.hpp, source/d3d8to9_device.cpp
In D3D8 a call to `BeginStateBlock()` starts state recording and also causes other state block calls (with the exception of `EndStateBlock()`) to fail. D3D9 does not handle this state block call validation behavior automatically, since some calls such as `DeleteStateBlock()` are missing altogether.
=> Validate state block calls during state recording

source/d3d8to9_device.cpp
D3D8 has some specific pointer clearing behavior around D3DFMT_UNKNOWN format validations. These fix several Wine tests, but also [a test I wrote myself](https://github.com/WinterSnowfall/d8vk-tests/commit/059f96ab14854e01c0b2ffa9fb2126cb01e8a91b) that passes on native D3D8.
=> Add D3DFMT_UNKNOWN checks on object creation

source/d3d8to9.cpp
Apparently using non-const char* causes warnings/errors with some C++ compilers, and this *should* be more palatable in general. @ThirteenAG Please let me know if this fixes the problem you were seeing.
=> Fix some char* assignment compiler warnings

source/d3d8to9.hpp, source/d3d8to9_base.cpp, source/d3d8to9_device.cpp
Not entirely sure why this wasn't being done in the first place, as devices created with D3DCREATE_MIXED_VERTEXPROCESSING expect this to work properly and there are some games that require dynamically switching between the two.
In the case of either D3DCREATE_SOFTWARE_VERTEXPROCESSING or D3DCREATE_HARDWARE_VERTEXPROCESSING devices, the call to `SetSoftwareVertexProcessing()` will simply fail, but we can safely ignore that. In fact D3D8 will never return anything other than D3D_OK for any `SetRenderState()` calls.
=> Setup SWVP toggle for mixed mode devices

source/d3d8to9_surface.cpp, source/d3d8to9_volume.cpp
Reverts #185. I've written a more extensive test to run against both modern d3d9 drivers and Windows XP, and it appears d3d9 already performs the required content clears, so explicitly clearing pLockedRect/Box is quite superfluous. Sorry for the noise.
=> Revert clearing rect/volume content on surface/volume locks

source/d3d8to9_base.cpp, source/d3d8to9_device.cpp, source/d3d8types.cpp
I'm not entirely sure why the existing logic was set up in the first place.
The MultiSampleQuality parameter in D3D9 is only intended for use with `D3DMULTISAMPLE_NONMASKABLE`, which is not available in D3D8.
This is implied by the official documentation as well:
> D3DMULTISAMPLE_NONMASKABLE
>     Enables the multisample quality value. See Remarks.
> Whether the display device supports maskable multisampling (more than one sample for a multiple-sample render-target format plus antialias support) or just non-maskable multisampling (only antialias support), the driver for the device provides the number of quality levels for the D3DMULTISAMPLE_NONMASKABLE multiple-sample type.
Therefore, while the current code doesn't do any harm, it is rather pointlessly issuing redundant queries to D3D9, …
=> Default to using 0 for MultiSampleQuality

source/d3d8to9.cpp
Just noticed this isn't getting printed in the usual/expected format vs the other loggers. Not sure where I was going with this originally, but it probably got copy-pasted and missed before pushing.
=> Fix DebugSetMute log message
